call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline-themes'

Plug 'vim-airline/vim-airline'

Plug 'rdnetto/ycm-generator'

Plug 'sjl/badwolf'

Plug 'shougo/deoplete.nvim'

Plug 'nsf/gocode'

Plug 'tomasr/molokai'

Plug 'ajh17/spacegray.vim'

Plug 'myhere/vim-nodejs-complete'

Plug 'sainnhe/forest-night'

" Initialize plugin system
call plug#end()

" for delete key to work
set backspace=indent,eol,start

colorscheme forest-night

let g:airline_theme = 'badwolf'

" air-line
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''
